services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: novaprofile-api
    env_file: .env
    environment:
      PYTHONUNBUFFERED: "1"
      TZ: Europe/Berlin
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped
