version: "3.9"
services:
  api:
    build: .
    container_name: novaprofile-api
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
