"""roles_assessments_and_more

Revision ID: e20a22ae1c26
Revises: 3f50d66fe9b5
Create Date: 2025-09-11 09:21:29.332479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e20a22ae1c26'
down_revision: Union[str, None] = '3f50d66fe9b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('division', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'archived', name='rolestatus'), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('responsibilities', sa.JSON(), nullable=False),
    sa.Column('kpi', sa.JSON(), nullable=False),
    sa.Column('competency_map', sa.JSON(), nullable=False),
    sa.Column('assessment_guidelines', sa.JSON(), nullable=False),
    sa.Column('test_assignment', sa.JSON(), nullable=False),
    sa.Column('assessment_center', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_division'), 'roles', ['division'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=False)
    op.create_table('assessments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessments_employee_id'), 'assessments', ['employee_id'], unique=False)
    op.create_index(op.f('ix_assessments_role_id'), 'assessments', ['role_id'], unique=False)
    op.create_table('career_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('role_title', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=255), nullable=False),
    sa.Column('unit', sa.String(length=255), nullable=False),
    sa.Column('started_at', sa.Date(), nullable=False),
    sa.Column('ended_at', sa.Date(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_history_employee_id'), 'career_history', ['employee_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_employee_id'), 'reviews', ['employee_id'], unique=False)
    op.create_table('succession',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('target_role', sa.Uuid(), nullable=False),
    sa.Column('is_starred', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_role'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_succession_employee_id'), 'succession', ['employee_id'], unique=False)
    op.create_index(op.f('ix_succession_is_starred'), 'succession', ['is_starred'], unique=False)
    op.create_index(op.f('ix_succession_target_role'), 'succession', ['target_role'], unique=False)
    op.create_table('vacancies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('department', sa.String(length=255), nullable=False),
    sa.Column('unit', sa.String(length=255), nullable=False),
    sa.Column('manager_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('open', 'hold', 'closed', name='vacancystatus'), nullable=False),
    sa.Column('headcount', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vacancies_department'), 'vacancies', ['department'], unique=False)
    op.create_index(op.f('ix_vacancies_manager_id'), 'vacancies', ['manager_id'], unique=False)
    op.create_index(op.f('ix_vacancies_role_id'), 'vacancies', ['role_id'], unique=False)
    op.create_index(op.f('ix_vacancies_status'), 'vacancies', ['status'], unique=False)
    op.create_index(op.f('ix_vacancies_unit'), 'vacancies', ['unit'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vacancies_unit'), table_name='vacancies')
    op.drop_index(op.f('ix_vacancies_status'), table_name='vacancies')
    op.drop_index(op.f('ix_vacancies_role_id'), table_name='vacancies')
    op.drop_index(op.f('ix_vacancies_manager_id'), table_name='vacancies')
    op.drop_index(op.f('ix_vacancies_department'), table_name='vacancies')
    op.drop_table('vacancies')
    op.drop_index(op.f('ix_succession_target_role'), table_name='succession')
    op.drop_index(op.f('ix_succession_is_starred'), table_name='succession')
    op.drop_index(op.f('ix_succession_employee_id'), table_name='succession')
    op.drop_table('succession')
    op.drop_index(op.f('ix_reviews_employee_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_career_history_employee_id'), table_name='career_history')
    op.drop_table('career_history')
    op.drop_index(op.f('ix_assessments_role_id'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_employee_id'), table_name='assessments')
    op.drop_table('assessments')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_division'), table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
