// src/lib/modules.js
export const ALL_COMPETENCIES = [
  "Стратегическое мышление",
  "Переговоры",
  "Аналитика",
  "Коммуникация",
  "Лидерство",
  "Финансовое мышление",
  "Тайм-менеджмент",
  "Проектное управление",
];

// ——— Роли
export const initialRoles = [
  {
    id: 1,
    name: "RM",
    version: "v1.0",
    kpi: "Рост продаж 10%",
    created: "2025-08-01",
    competencies: {
      "Стратегическое мышление": 3,
      "Переговоры": 2,
      "Коммуникация": 4,
      "Тайм-менеджмент": 4,
      "Проектное управление": 3,
    },
  },
  {
    id: 2,
    name: "KAM",
    version: "v1.0",
    kpi: "Рост продаж 15%",
    created: "2025-08-02",
    competencies: {
      "Стратегическое мышление": 4,
      "Аналитика": 3,
      "Переговоры": 4,
      "Коммуникация": 4,
      "Финансовое мышление": 3,
    },
  },
  {
    id: 3,
    name: "GKAM (Electronics)",
    version: "v1.0",
    kpi: "Доля полки +20%, NPS ключевых сетей +10",
    created: "2025-08-10",
    competencies: {
      "Стратегическое мышление": 4,
      "Аналитика": 4,
      "Переговоры": 4,
      "Лидерство": 4,
      "Финансовое мышление": 3,
    },
  },
  {
    id: 4,
    name: "Руководитель отдела обучения",
    version: "v1.0",
    kpi: "Снижение time-to-productivity -20%",
    created: "2025-08-15",
    competencies: {
      "Лидерство": 4,
      "Коммуникация": 4,
      "Проектное управление": 4,
      "Стратегическое мышление": 3,
      "Аналитика": 3,
    },
  },
  {
    id: 5,
    name: "CEO",
    version: "v1.0",
    kpi: "EBITDA +15%",
    created: "2025-08-20",
    competencies: {
      "Стратегическое мышление": 4,
      "Лидерство": 4,
      "Финансовое мышление": 4,
      "Коммуникация": 4,
      "Аналитика": 4,
    },
  },
];

// ——— Стандарты ролей (карточки-«эталоны») — подсовываем 4 примера
export const roleStandards = [
  {
    id: "std_kam_v1",
    status: "active",
    name: "KAM",
    version: "v1.0",
    division: "Sales / FMCG",
    goal: "Рост продаж в ключевых сетях и устойчивость листинга.",
    responsibilities: [
      "Планирование и защита JBP",
      "Управление промо и листингом",
      "Синхронизация маркетинга и логистики",
    ],
    kpi: {
      current: [
        { name: "Рост sell-out", target: "+8% QoQ", period: "квартал" },
        { name: "Доля полки в ТОП-5 сетей", target: "≥95%", period: "месяц" },
      ],
      recommended: [
        { name: "Маржинальность категории", target: "≥X%", period: "квартал" },
        { name: "NPS сетей", target: "+10", period: "полугодие" },
      ],
    },
    competencyMap: {
      "Стратегическое мышление": 4,
      "Переговоры": 4,
      "Аналитика": 3,
      "Коммуникация": 4,
      "Лидерство": 3,
      "Финансовое мышление": 3,
      "Тайм-менеджмент": 3,
      "Проектное управление": 3,
    },
    assessmentGuidelines: {
      scales: "Шкала 1–4 с поведенческими индикаторами на каждый уровень.",
      behavioralAnchors: {
        "Переговоры": [
          "Готовит BATNA; фиксирует договорённости письменно",
          "Управляет повесткой и рамками встречи",
        ],
      },
      evidenceExamples: ["Снижение OOS на 30%", "JBP с X5 на Q3"],
    },
    testAssignment: {
      objective: "Собрать JBP на 6 месяцев для сети Y",
      deliverables: ["Презентация 10 слайдов", "Мини-модель P&L"],
      evaluationCriteria: ["Логика гипотез", "Финансовая обоснованность", "План рисков"],
      timeboxHours: 8,
    },
    assessmentCenter: {
      cases: [
        {
          title: "Эскалация с категорией",
          durationMin: 30,
          observersRoles: ["HRBP", "Sales Director"],
          competenciesObserved: ["Коммуникация", "Переговоры", "Лидерство"],
        },
      ],
      rubrics: "Матрица Компетенции × Поведенческие индикаторы",
    },
    tags: ["retail", "sales"],
    createdAt: "2025-08-10",
    updatedAt: "2025-08-10",
  },
  {
    id: "std_rm_v1",
    status: "active",
    name: "RM",
    version: "v1.0",
    division: "Sales / Regions",
    goal: "Обеспечить выполнение плана продаж в регионе и качественную операционку.",
    responsibilities: ["Управление территорией", "Координация промо", "Витрины и выкладка"],
    kpi: {
      current: [
        { name: "Выполнение плана sell-in", target: "≥100%", period: "месяц" },
        { name: "SKU в наличии", target: "≥98%", period: "месяц" },
      ],
      recommended: [
        { name: "Скорость закрытия out-of-stock", target: "≤24ч", period: "месяц" },
      ],
    },
    competencyMap: {
      "Коммуникация": 4, "Переговоры": 2, "Стратегическое мышление": 3, "Тайм-менеджмент": 4, "Проектное управление": 3
    },
    assessmentGuidelines: { scales: "1–4", behavioralAnchors: {}, evidenceExamples: [] },
    testAssignment: { objective: "План полочного пространства", deliverables: ["Excel план"], evaluationCriteria: ["Логика", "Данные"], timeboxHours: 4 },
    assessmentCenter: { cases: [], rubrics: "" },
    tags: ["regions"],
    createdAt: "2025-08-15",
    updatedAt: "2025-08-15",
  },
  {
    id: "std_gkam_el_v1",
    status: "active",
    name: "GKAM (Electronics)",
    version: "v1.0",
    division: "Sales / Electronics",
    goal: "Развитие электроники в ключевых сетях и защита маржи.",
    responsibilities: ["JBP электроника", "Категорийная аналитика", "Переговоры с HQ"],
    kpi: {
      current: [
        { name: "Доля полки электроника", target: "+20%", period: "квартал" },
      ],
      recommended: [
        { name: "GM электроника", target: "≥X%", period: "квартал" },
      ],
    },
    competencyMap: {
      "Стратегическое мышление": 4, "Аналитика": 4, "Переговоры": 4, "Лидерство": 4, "Финансовое мышление": 3
    },
    assessmentGuidelines: { scales: "1–4", behavioralAnchors: {}, evidenceExamples: [] },
    testAssignment: { objective: "Категорийная стратегия", deliverables: ["Презентация"], evaluationCriteria: ["Факты/гипотезы"], timeboxHours: 10 },
    assessmentCenter: { cases: [], rubrics: "" },
    tags: ["electronics"],
    createdAt: "2025-08-20",
    updatedAt: "2025-08-20",
  },
  {
    id: "std_lnd_head_v1",
    status: "active",
    name: "Руководитель отдела обучения",
    version: "v1.0",
    division: "L&D",
    goal: "Сократить time-to-productivity и масштабировать компетенции.",
    responsibilities: ["Дизайн курсов", "Оценка эффективности", "Наставничество"],
    kpi: {
      current: [{ name: "Вовлечённость в обучение", target: "≥70%", period: "квартал" }],
      recommended: [{ name: "TtP (нед.)", target: "-20%", period: "полугодие" }],
    },
    competencyMap: { "Лидерство": 4, "Коммуникация": 4, "Проектное управление": 4, "Аналитика": 3, "Стратегическое мышление": 3 },
    assessmentGuidelines: { scales: "1–4", behavioralAnchors: {}, evidenceExamples: [] },
    testAssignment: { objective: "Roadmap обучения", deliverables: ["Roadmap"], evaluationCriteria: ["Цели/метрики"], timeboxHours: 8 },
    assessmentCenter: { cases: [], rubrics: "" },
    tags: ["lnd"],
    createdAt: "2025-08-22",
    updatedAt: "2025-08-22",
  },
];

// ——— Сотрудники (12 профилей)
export const initialEmployees = [
  { id: 101, name: "Иван Иванов", title: "RM", department: "Продажи", region: "ЦФО",
    readiness: { targetRole: "KAM", percent: 72 },
    competencies: { "Стратегическое мышление": 3, "Переговоры": 3, "Коммуникация": 4, "Тайм-менеджмент": 4 },
    assessments: [{ date: "2025-05", percent: 60 },{ date: "2025-06", percent: 68 },{ date: "2025-07", percent: 72 }],
    lastAssessment: "2025-07",
    bio: "5 лет в FMCG; федеральные сети; усиливает коммуникацию, стабильно закрывает операционку." },
  { id: 102, name: "Анна Петрова", title: "RM", department: "Продажи", region: "ПФО",
    readiness: { targetRole: "KAM", percent: 65 },
    competencies: { "Стратегическое мышление": 2, "Переговоры": 3, "Аналитика": 2, "Коммуникация": 4 },
    assessments: [{ date: "2025-05", percent: 55 },{ date: "2025-06", percent: 61 },{ date: "2025-07", percent: 65 }],
    lastAssessment: "2025-07",
    bio: "4 года в полевом мерче; сильная дисциплина; хочет развить переговоры." },
  { id: 103, name: "Дмитрий Кузнецов", title: "KAM", department: "Продажи", region: "СЗФО",
    readiness: { targetRole: "GKAM (Electronics)", percent: 88 },
    competencies: { "Стратегическое мышление": 4, "Аналитика": 4, "Переговоры": 3, "Коммуникация": 4 },
    assessments: [{ date: "2025-05", percent: 78 },{ date: "2025-06", percent: 84 },{ date: "2025-07", percent: 88 }],
    lastAssessment: "2025-07",
    bio: "7 лет в ключевых клиентах; 2 JBP; улучшил долю полки в ТОП-3 сетях." },
  { id: 104, name: "Мария Волконская", title: "Руководитель отдела обучения", department: "L&D", region: "ЦФО",
    readiness: { targetRole: "CEO", percent: 54 },
    competencies: { "Лидерство": 4, "Коммуникация": 4, "Проектное управление": 4, "Аналитика": 3, "Стратегическое мышление": 3 },
    assessments: [{ date: "2025-06", percent: 52 },{ date: "2025-07", percent: 54 }],
    lastAssessment: "2025-07",
    bio: "10 лет в обучении; строит корпоративные академии; про TtP думает как инженер." },
  { id: 105, name: "Сергей Брагин", title: "KAM", department: "Продажи", region: "ЮФО",
    readiness: { targetRole: "GKAM (Electronics)", percent: 74 },
    competencies: { "Переговоры": 4, "Коммуникация": 4, "Аналитика": 3, "Стратегическое мышление": 3 },
    assessments: [{ date: "2025-05", percent: 68 },{ date: "2025-06", percent: 70 },{ date: "2025-07", percent: 74 }],
    lastAssessment: "2025-07",
    bio: "12 лет в продажах; обожает структурировать аргументацию и вести сложные встречи." },
  { id: 106, name: "Екатерина Алексеева", title: "RM", department: "Продажи", region: "СФО",
    readiness: { targetRole: "KAM", percent: 61 },
    competencies: { "Коммуникация": 4, "Переговоры": 3, "Тайм-менеджмент": 4, "Проектное управление": 3 },
    assessments: [{ date: "2025-05", percent: 53 },{ date: "2025-06", percent: 57 },{ date: "2025-07", percent: 61 }],
    lastAssessment: "2025-07",
    bio: "Карьерный RM; прокачивает аналитику; любит чек-листы и стандарты торгового зала." },
  { id: 107, name: "Илья Можаев", title: "RM", department: "Продажи", region: "ДФО",
    readiness: { targetRole: "KAM", percent: 58 },
    competencies: { "Коммуникация": 3, "Переговоры": 2, "Тайм-менеджмент": 4, "Стратегическое мышление": 2 },
    assessments: [{ date: "2025-05", percent: 50 },{ date: "2025-06", percent: 54 },{ date: "2025-07", percent: 58 }],
    lastAssessment: "2025-07",
    bio: "Сильный в операционке, развивает переговоры; закрывает OOS быстрее среднего." },
  { id: 108, name: "Полина Жданова", title: "KAM", department: "Продажи", region: "УФО",
    readiness: { targetRole: "GKAM (Electronics)", percent: 79 },
    competencies: { "Переговоры": 4, "Коммуникация": 4, "Аналитика": 3, "Финансовое мышление": 3 },
    assessments: [{ date: "2025-05", percent: 70 },{ date: "2025-06", percent: 75 },{ date: "2025-07", percent: 79 }],
    lastAssessment: "2025-07",
    bio: "Умеет переводить JBP в конкретные цифры; любит строить промо-календарь от unit-экономики." },
  { id: 109, name: "Артём Ким", title: "CEO", department: "HQ", region: "Москва",
    readiness: { targetRole: "CEO", percent: 91 },
    competencies: { "Стратегическое мышление": 4, "Лидерство": 4, "Финансовое мышление": 4, "Коммуникация": 4, "Аналитика": 4 },
    assessments: [{ date: "2025-07", percent: 91 }],
    lastAssessment: "2025-07",
    bio: "15 лет в топ-менеджменте; собирает сбалансированные портфели направлений." },
  { id: 110, name: "Ольга Летовская", title: "RM", department: "Продажи", region: "СЗФО",
    readiness: { targetRole: "KAM", percent: 67 },
    competencies: { "Коммуникация": 4, "Проектное управление": 3, "Тайм-менеджмент": 4, "Переговоры": 3 },
    assessments: [{ date: "2025-05", percent: 59 },{ date: "2025-06", percent: 63 },{ date: "2025-07", percent: 67 }],
    lastAssessment: "2025-07",
    bio: "Любит операционные апгрейды: чек-листы, SLA, шаблоны писем; дисциплина как у часов." },
  { id: 111, name: "Фёдор Глазьев", title: "KAM", department: "Продажи", region: "ЦФО",
    readiness: { targetRole: "GKAM (Electronics)", percent: 82 },
    competencies: { "Переговоры": 4, "Коммуникация": 4, "Стратегическое мышление": 4, "Аналитика": 3 },
    assessments: [{ date: "2025-05", percent: 76 },{ date: "2025-06", percent: 79 },{ date: "2025-07", percent: 82 }],
    lastAssessment: "2025-07",
    bio: "Спокоен в переговорах; быстро разруливает эскалации; понимает KPI сети." },
  { id: 112, name: "Светлана Маликова", title: "RM", department: "Продажи", region: "ПФО",
    readiness: { targetRole: "KAM", percent: 63 },
    competencies: { "Коммуникация": 3, "Переговоры": 3, "Стратегическое мышление": 2, "Проектное управление": 3 },
    assessments: [{ date: "2025-05", percent: 56 },{ date: "2025-06", percent: 60 },{ date: "2025-07", percent: 63 }],
    lastAssessment: "2025-07",
    bio: "Умеет дружить с операционкой; теперь идёт в сторону категорийной аналитики." },
];
